name: approval_app
description: Aplikasi Approval Cuti, Ijin, Sakit, dan Overtime

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true